### ISSUE TITLE
[FIX] 플레이 캐스트 액티비티 updateUI가 audioFragment만 반영

### ISSUE THREAD

**Issue by wslee6704** [umc-owncast/Owncast_frontend#50]
재생목록의 이전, 다음버튼을 눌렀을때, audioFragment가 띄워져있을때만 정보가 수정됨
플리를 띄웠을때와 script를 띄웠을때 정보를 반영하게 각각 바꿔줘야함

**Comment by wslee6704** [comment]
우선 updateUi를 쓸때도 있고 안쓰고 그냥 audioFragment 바꿔놓을때도 있어서 따로 when으로 넣어놨어 영준

**Comment by dori-04** [comment]
오 굳굳
